import exception
try:
    print(1/2)
except:
    raise RuntimeError ("something happened ") 